### Imports

In [3]:
import numpy as np

## Q1
Create a 3x3 array that contains a diagonal of nines.

In [23]:
q1=np.eye(3,dtype=np.int64)*9
print(q1)

[[9 0 0]
 [0 9 0]
 [0 0 9]]


## Q2
Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) and use Boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.

In [24]:
q2 = np.arange(2,34,2).reshape(4,4)
mean = q2.mean()
std = q2.std()
q2 = q2[(q2<= mean +0.5 * std )&(q2>=mean-0.5*std)]
print(q2)

[14 16 18 20]


## Q3
Create a 9x9 array that contains only zero of type int.

In [25]:
q3 = np.zeros((9,9),dtype=np.int64)
print(q3)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


## Q4
Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that has its first column full of ones, its second column full of twos, its third column full of threes, etc…

In [26]:
n = int(input("Enter Number : "))

Enter Number :  5


In [30]:
c= np.ones((n,1),dtype=int)
r= np.arange(1,n+1,1)
q4=c*r
print(q4)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
